# Generated by Django 4.0.3 on 2022-05-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('qualifications', models.TextField()),
                ('requirements', models.TextField()),
                ('additional_info', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditions', to='profiles.profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditions', to='auditions.auditiontype')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
